# fly.toml app configuration file generated for hwapi on 2025-01-08T14:05:56-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hwapi'
primary_region = 'sea'

[build]
  command = "./hwapi"


[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "homework"
  destination = "/data/"
